# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('Codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Tamano', models.CharField(max_length=4)),
                ('Peso', models.CharField(max_length=4)),
                ('Color', models.CharField(max_length=7)),
                ('Descripcion', models.TextField()),
                ('FechaRescate', models.DateField()),
                ('Estado', models.CharField(max_length=32)),
            ],
        ),
    ]
