# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rescatados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='rescatado',
            name='vacuna',
            field=models.ManyToManyField(to='Rescatados.Vacuna'),
        ),
    ]
