# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Domicilio',
            field=models.CharField(max_length=50),
        ),
    ]
